unpackaged/main/default/objects/Account/fields/litify_pm__First_Name__c.field-meta.xml
<CustomField>
    <fullName>litify_pm__First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/litify_pm__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>litify_pm__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/litify_pm__Role__c/litify_pm__Role__c.object-meta.xml
<CustomObject>
    <description>The junction object defines the role between Party (Account) and Intakes or Matter object</description>
    <label>Role</label>
    <nameField>
        <displayFormat>ROL-{0}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/litify_pm__Role__c/fields/litify_pm__Party__c.field-meta.xml
<CustomField>
    <fullName>litify_pm__Party__c</fullName>
    <label>Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/litify_pm__Role__c/fields/litify_pm__Role__c.field-meta.xml
<CustomField>
    <fullName>litify_pm__Role__c</fullName>
    <label>Role Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Health Care Facility</fullName>
            </value>
            <value>
                <fullName>Insurance Company</fullName>
            </value>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Judge</fullName>
            </value>
            <value>
                <fullName>Jury Member</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Plaintiff</fullName>
            </value>
            <value>
                <fullName>Police Department</fullName>
            </value>
            <value>
                <fullName>Records Provider</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Caller</fullName>
                <isActive>false</isActive>
                <label>Caller</label>
            </value>
            <value>
                <fullName>Employer</fullName>
                <isActive>false</isActive>
                <label>Employer</label>
            </value>
            <value>
                <fullName>Injured Party</fullName>
                <isActive>false</isActive>
                <label>Injured Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/RoleTriggerTest.cls
@isTest
public class RoleTriggerTest {
    @isTest static void createNewParty(){
        Account party = new Account();
        party.Name = 'Test Account';
        party.litify_pm__First_Name__c = 'Test';  
        party.litify_pm__Last_Name__c = 'Account';
        
        insert party;

       	litify_pm__Role__c role = new litify_pm__Role__c();
        role.litify_pm__Party__c = party.Id;
        
        insert role;
        delete role;
    }
}